#!/bin/bash

VANTRASH=/var/www/vantrash
export PERL5LIB="$VANTRASH/lib"

exec 2>&1 \
    /usr/local/bin/starman --listen 127.0.0.1:2080 --workers 4 --preload-app \
        --user vantrash --group www-data \
        $VANTRASH/production.psgi >> /var/log/vantrash-server.log 2>&1
